version: '3'

services:
  web:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - FLASK_URL = "http://flask:5000"
    depends_on:
      - flask

  flask:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile.flask
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports: 
      - "5000:5000" 
    depends_on:
      - postgres
    
  postgres:
    container_name: "postgres-db"
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER = $POSTGRES_USER
      - POSTGRES_PASSWORD = $POSTGRES_PASSWORD
      - POSTGRES_DB = $POSTGRES_DB 
    volumes:
      - $POSTGRES_PATH:/var/lib/postgresql/data
    ports:
      - "5432:5432"